services:
  torir-studio:
    build:
      context: ./rstudio
    environment:
      DISABLE_AUTH: "true"
    ports:
    - 127.0.0.1:8787:8787
    volumes:
    - ./data:/home/rstudio/data
version: "3.2"